util:log: Added log_time decorator
intel/dffml pull request #1101
Opened 2021-04-14 05:54 UTC by programmer290399

* Fixes: #1088 
* Ready for review

2021-05-21 16:49 UTC, programmer290399 commented
Both the failing tests :  `Tests / test (., 3.7)` &  `Tests / test (., 3.8) ` have the same error `ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device`

2021-05-24 14:00 UTC, pdxjohnny commented on CHANGELOG.md
> +
Remove superfluous whitespace change

```suggestion
```

2021-05-24 16:27 UTC, pdxjohnny requested changes

2021-05-24 16:27 UTC, pdxjohnny commented on dffml/util/log.py
> +    Found on Stack Overflow from Mikhail Gerasimov, only modified
If we include third party code in the main package it has to go through legal review again, which is not something that we can do at this point. This code isn't ideal anyway,  we really don't need to borrow from anywhere, we have all the pieces already.

We should be using a monotonic clock.

We should try to wrap any kind of function, coroutine, or generator, using the code we had here (or something similar or better)

https://github.com/intel/dffml/blob/b66b8bd298bfc1ba347afd5733bc36cc5ded1ab0/dffml/util/net.py#L172-L222

2021-05-25 00:42 UTC, programmer290399 commented on dffml/util/log.py
> +    Found on Stack Overflow from Mikhail Gerasimov, only modified
okay , I wasn't aware about that we need legal reviews for adding third party code, just saw something similar in `dffml/service/dev.py` in `remove_ansi_escape` method of `PinDeps` CMD , so I thought it would be fine to use code as it is from third party sources, if give proper credit, 

However I will re-write this little part and take care of this point in future.....

2021-05-25 01:59 UTC, pdxjohnny commented on dffml/util/log.py
> +    Found on Stack Overflow from Mikhail Gerasimov, only modified
Ahhhhhh yes, thank you, that code should have been removed before release. Good catch

2021-06-02 13:24 UTC, programmer290399 commented on dffml/util/log.py
> +    Found on Stack Overflow from Mikhail Gerasimov, only modified
Updated :) , I think it should be fine now

2021-06-03 17:02 UTC, pdxjohnny commented
This PR doesn't include examples `>>> ` (you may need to look into `tests/test_docstrings.py` `wrap_` stuff). We also need to make sure it works for all function types, as per this reference: 
https://github.com/intel/dffml/blob/b66b8bd298bfc1ba347afd5733bc36cc5ded1ab0/dffml/util/net.py#L172-L222

2021-06-04 15:50 UTC, programmer290399 commented
Ok , would look into this

2021-06-04 17:59 UTC, pdxjohnny commented
Ya good point, no reason to do generator functions, my bad.

Let's make sure we have the docstrings though

2021-07-14 06:31 UTC, programmer290399 commented
waiting for #1132

2021-07-27 16:38 UTC, merged