docs: conf: Add download button for ipython notebooks
intel/dffml pull request #1118
Opened 2021-05-21 08:35 UTC by mHash1m

Signed-off-by: mHash1m <hashimchaudry23@gmail.com>

2021-05-24 17:12 UTC, pdxjohnny requested changes

2021-05-25 09:00 UTC, mHash1m commented on docs/conf.py
> +    :target: https://intel.github.io/dffml/master/{{docname[:-6]}}ipynb
@pdxjohnny I've pushed the changes, please check if I understood this correctly.

2021-05-25 09:04 UTC, mHash1m commented on docs/conf.py
> +    :target: https://intel.github.io/dffml/master/{{docname[:-6]}}ipynb
Although, this also causes the button to fail on local until the next release.

2021-05-25 17:20 UTC, pdxjohnny approved these changes

2021-05-25 17:21 UTC, merged