dffml: plugins: Added OS check for autosklearn; Fixes #887
intel/dffml pull request #889
Opened 2020-11-10 04:20 UTC by SGeetansh

Added an OS check to exclude/include autosklearn into the core plugins.

2020-11-10 14:26 UTC, yashlamba commented
You can remove model/autosklearn from the below locations to test it with CI.
https://github.com/intel/dffml/blob/8087819432a187073d2acdde07e02ff8703bfc19/.github/workflows/testing.yml#L196
and
https://github.com/intel/dffml/blob/8087819432a187073d2acdde07e02ff8703bfc19/.github/workflows/testing.yml#L233

2020-11-10 14:52 UTC, SGeetansh commented
@yashlamba Okay.

2020-11-10 15:43 UTC, yashlamba commented on dffml/plugins.py
> +if platform.system() in {"Windows", "Darwin"}:
```suggestion
if platform.system() not in {"Windows", "Darwin"}:
```

2020-11-10 16:17 UTC, yashlamba commented
You'll need to add similar checks here again:
https://github.com/intel/dffml/blob/8087819432a187073d2acdde07e02ff8703bfc19/dffml/plugins.py#L102-L123

2020-11-11 17:26 UTC, yashlamba approved these changes
Looks good!

2020-11-12 17:03 UTC, pdxjohnny requested changes

2020-11-12 17:03 UTC, pdxjohnny commented on dffml/plugins.py
> +    and not python_package_installed("auto_sklearn")
```suggestion
    and not python_package_installed("autosklearn")
```

Package name has no `_`

2020-11-14 19:36 UTC, merged

2020-11-14 19:37 UTC, pdxjohnny commented
Thank you! I must have forgot to hit the merge button the other day when I looked at this. Sorry for the delay!