model: pytorch: Custom exception when loss function is misspelled
intel/dffml pull request #917
Opened 2020-12-05 05:03 UTC by nitesh585

solved issue #910.

Exception message
before change - "AttributeError : 'NoneType' object has no attribute 'function' ".
after change - "LossFunctionNotFoundError : Loss function is not valid ".

2020-12-06 03:38 UTC, pdxjohnny requested changes

2020-12-06 03:38 UTC, pdxjohnny commented on model/pytorch/dffml_model_pytorch/pytorch_base.py
> +        Exception raised when loss function is misspelled.
```suggestion
    Exception raised when loss function is misspelled.
```

2020-12-06 03:38 UTC, pdxjohnny commented on model/pytorch/dffml_model_pytorch/pytorch_base.py
> +        super().__init__(self.message)
```suggestion
```

We don't need `__init__`. It is sufficient to just pass tje error message every time. If possible , we should report what the spelling the use gave that didn't work.

2020-12-06 03:38 UTC, pdxjohnny commented on model/pytorch/dffml_model_pytorch/pytorch_base.py
> +            raise LossFunctionNotFoundError()
```python
            raise LossFunctionNotFoundError(f"Loss function is not valid! Function name given was {<TODO: Figure out what variable would hold the original spelling>}")
```

2020-12-06 04:32 UTC, nitesh585 commented on model/pytorch/dffml_model_pytorch/pytorch_base.py
> +            raise LossFunctionNotFoundError()
Sure! Will try to figure out this.

2020-12-06 18:04 UTC, nitesh585 commented
Can't have access to loss function name given by the user in `./model/pytorch/dffml_model_pytorch/pytorch_base.py`.
The file where we can find that is   `./model/pytorch/dffml_model_pytorch/utils/utils.py`. So, I have changed it accordingly.

2020-12-08 17:53 UTC, pdxjohnny commented on model/pytorch/dffml_model_pytorch/utils/utils.py
> +    pass
```suggestion
```

2020-12-08 18:44 UTC, nitesh585 commented on model/pytorch/dffml_model_pytorch/utils/utils.py
> +    pass
@pdxjohnny Please review my latest commit. I have made all those changes.

2020-12-09 05:30 UTC, pdxjohnny commented
Great work!

2020-12-09 05:31 UTC, merged